apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: leases.dhcp.johnsonjeff.com
spec:
  group: dhcp.johnsonjeff.com
  names:
    kind: Lease
    plural: leases
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            expiration:
              type: string
            hostname:
              type: string
            mac:
              type: string
          required:
          - mac
          - expiration
          - hostname
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
