apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: ranges.dhcp.johnsonjeff.com
spec:
  group: dhcp.johnsonjeff.com
  names:
    kind: Range
    plural: ranges
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cidr:
              type: string
            dns:
              items:
                type: string
              type: array
            router:
              type: string
            subnetmask:
              type: string
          required:
          - cidr
          - router
          - subnetmask
          - dns
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
