apiVersion: dhcp.johnsonjeff.com/v1alpha1
kind: Range
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: range-sample
  namespace: network
spec:
  cidr: "10.10.0.128/25"
  router: "10.10.0.1"
  subnetmask: "255.255.0.0"
  dns: "10.0.0.1"