on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/github.com/johnsonj
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14.2
    - run: find .
